{
  "LagaRhino": "LagaRhino.yml",
  "LagaRhino.CurveData": "LagaRhino.CurveData.yml",
  "LagaRhino.CurveData.CorrectPlaneOnCurveByParam(Rhino.Geometry.Curve,System.Double)": "LagaRhino.CurveData.yml",
  "LagaRhino.CurveData.DeepCopyListCurve(System.Collections.Generic.List{Rhino.Geometry.Curve})": "LagaRhino.CurveData.yml",
  "LagaRhino.CurveData.GetPointFromCurves(System.Collections.Generic.List{Rhino.Geometry.Curve},System.Double)": "LagaRhino.CurveData.yml",
  "LagaRhino.LineCurveData": "LagaRhino.LineCurveData.yml",
  "LagaRhino.LineCurveData.Axis(Rhino.Geometry.LineCurve)": "LagaRhino.LineCurveData.yml",
  "LagaRhino.PointData": "LagaRhino.PointData.yml",
  "LagaRhino.PointData.GroupByZ(Rhino.Geometry.Point3d[])": "LagaRhino.PointData.yml",
  "LagaRhino.PointData.MirrorPointQuadrant(Rhino.Geometry.Point3d)": "LagaRhino.PointData.yml",
  "LagaRhino.PointData.Point3dToVector(Rhino.Geometry.Point3d)": "LagaRhino.PointData.yml",
  "LagaRhino.PointData.PointQuadrant(Rhino.Geometry.Point3d)": "LagaRhino.PointData.yml",
  "LagaRhino.PointData.SortPointsByXY(Rhino.Geometry.Point3d[])": "LagaRhino.PointData.yml",
  "LagaRhino.PointData.SortPointsByZ(Rhino.Geometry.Point3d[])": "LagaRhino.PointData.yml",
  "LagaRhino.PointData.TwoPointsInterpolation(Rhino.Geometry.Point3d,Rhino.Geometry.Point3d,System.Double)": "LagaRhino.PointData.yml",
  "LagaRhino.PointData.VectorToPoint3d(Laga.Geometry.Vector)": "LagaRhino.PointData.yml",
  "LagaRhino.Shoebox": "LagaRhino.Shoebox.yml",
  "LagaRhino.Shoebox.#ctor(Rhino.Geometry.Point3d,System.Double,System.Double,System.Double,System.Double)": "LagaRhino.Shoebox.yml",
  "LagaRhino.Shoebox.#ctor(Rhino.Geometry.Point3d,System.Double,System.Double,System.Double,System.Double,System.Double,System.Double,System.Double)": "LagaRhino.Shoebox.yml",
  "LagaRhino.Shoebox.Area": "LagaRhino.Shoebox.yml",
  "LagaRhino.Shoebox.ShoeBox": "LagaRhino.Shoebox.yml",
  "LagaRhino.Shoebox.Volume": "LagaRhino.Shoebox.yml",
  "LagaRhino.SurfaceData": "LagaRhino.SurfaceData.yml",
  "LagaRhino.SurfaceData.#ctor(Rhino.Geometry.Surface,System.Int32,System.Int32)": "LagaRhino.SurfaceData.yml",
  "LagaRhino.SurfaceData.PlaneSurfaceAxis(Rhino.Geometry.LineCurve,System.Double)": "LagaRhino.SurfaceData.yml",
  "LagaRhino.SurfaceData.SurfacePoints": "LagaRhino.SurfaceData.yml"
}